### ISSUE TITLE
RSocketWebSocketClient removes wrong error event listener

### ISSUE THREAD

**Issue by gsteen** [rsocket/rsocket-js#100]
https://github.com/rsocket/rsocket-js/blob/cde81cd793f7b60f00085e398543e8687b7964f1/packages/rsocket-websocket-client/src/RSocketWebSocketClient.js#L159

Shouldn't it be:

`(socket.removeEventListener: $FlowIssue)('error', this._handleError);`

**Comment by OlegDokuka** [comment]
closed by https://github.com/rsocket/rsocket-js/commit/6fb2aa519beda7066bebf3f18d7c4a82c2dfd7b1
