### ISSUE TITLE
Error code not available when rsocket connection establishment fails 

### ISSUE THREAD

**Issue by akulkarni-01** [rsocket/rsocket-js#106]
What is the recommended approach to access the error code when rsocket connection establishment fails ?
The error code will help determine the user experience .

Attached is the screenshot while debugging ,the error object does not have any information about the error code in  _this.handleError 

<img width="1059" alt="Screen Shot 2020-12-01 at 4 00 34 PM" src="https://user-images.githubusercontent.com/69484521/100810961-713d2e00-33ee-11eb-8a05-0e32524ecef4.png">

**Comment by OlegDokuka** [comment]
@akulkarni-01 I believe that it is impossible due to browser websocket API limitations https://stackoverflow.com/a/18804298/4891253

**Comment by akulkarni-01** [comment]
Thanks @OlegDokuka 
So if I am understanding it correctly it is a current limitation of the ws library that rsocket JS uses .
If that correct ?
https://github.com/rsocket/rsocket-js/blob/f85762d0780fb63dc19038fddea6adfc942b7eaf/package.json#L74

**Comment by OlegDokuka** [comment]
@akulkarni-01 we use a standard websocket api available at all the browsers. Behaviors may differ depends on the browser implementation

**Comment by OlegDokuka** [comment]
@akulkarni-01 for more information on the browser websocket specification use the following link -> https://html.spec.whatwg.org/multipage/web-sockets.html#the-websocket-interface. According to the spec, the [onerror](https://html.spec.whatwg.org/multipage/web-sockets.html#handler-websocket-onerror) event handler propagates an [error](https://html.spec.whatwg.org/multipage/indices.html#event-error) as  [`ErrorEvent`](https://html.spec.whatwg.org/multipage/webappapis.html#errorevent). And according to the spec, fields like `message` or `error` may or may not be set. Hence, we can nothing to do with that and the behavior depends on the particular browser implementation. We do not use any external libraries for the browser side and only for **nodejs** side relies on the [Node WebSocket](https://www.npmjs.com/package/ws) library
