### ISSUE TITLE
0.0.8 WebSocket Client Fails Flow Check

### ISSUE THREAD

**Issue by kbahr** [rsocket/rsocket-js#12]
I'm trying to integrate 0.0.8 for its fix to the RSocketWebSocketClient but my project fails to pass Flow type checks with this error:

> @ check /Users/kylebahr/Projects/proteus-js
> flow check --show-all-errors

Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
node_modules/rsocket-websocket-client/build/RSocketWebSocketClient.js.flow:129:27

Cannot call this._handleError with error bound to e because property error is
missing in Error [1] but exists in object type [2].

     node_modules/rsocket-websocket-client/build/RSocketWebSocketClient.js.flow
     126│       },
     127│       onError: error => {
     128│         subscription && this._senders.delete(subscription);
     129│         this._handleError(error);
     130│       },
     131│       onNext: frame => this._writeFrame(frame),
     132│       onSubscribe: _subscription => {
        :
 [2] 179│   _handleError = (e: {error: Error}): void => {

     node_modules/rsocket-types/build/ReactiveStreamTypes.js.flow
 [1]  62│   +onError?: (error: Error) => void,

**Comment by lexs** [comment]
@kbahr Do you want me to release a 0.0.9 for these fixes?

**Comment by kbahr** [comment]
At your leisure - I have a working Node app using the TCP RSocket and am not desperate to integrate Websocket seamlessly quite yet :). Thanks very much for the quick turnaround!
