### ISSUE TITLE
spring messaging `@ConnectMapping` not called for routes

### ISSUE THREAD

**Issue by bseber** [rsocket/rsocket-js#123]
hey o/

not sure if I'm right here 😊
(Just thought so since it works in a plain Java App. see [here](https://github.com/gregwhitaker/springboot-rsocketmetadatapush-example/blob/master/hello-service/src/main/java/example/service/hello/controller/HelloController.java#L28:L33) )

I've got a java (spring) controller with a `ConnectMapping` for a custom route:

```java
@Controller
public class WsController {

    @ConnectMapping("setup")
    public Mono connect() {
        System.out.println("Never called :-(");
        return Mono.empty();
    }
}
```

The JavaScript `RSocketClient`  sends the setup frame with the custom route:

```js
const client = new RSocketClient({
    serializers: {
        data: JsonSerializer,
        metadata: JsonSerializer,
    },
    setup: {
        keepAlive: 999999,
        lifetime: 999999,
        dataMimeType: "application/json",
        metadataMimeType: "message/x.rsocket.routing.v0",
        payload: {
            metadata: String.fromCharCode("setup".length) + "setup"
        }
    },
    transport: new RSocketWebSocketClient(
        {
            debug: true,
            url: `ws://${window.location.host}/rsocket`,
        }
    ),
});

client.connect().then(...)
```

But `WsController#connect` is never called.
It works, however, with a default `@ConnectMapping` and not sending a `payload` within the setup frame.

I've added a sample project that can be found here: https://github.com/bseber/spring-boot-rsocket-example

Should it work with the custom route? Do I have to configure the `RSocketClient` somehow?

**Comment by SentryMan** [comment]
I"m getting the same issue when I use composite metadata

**Comment by baudiachatb** [comment]
> ```js
> url: `ws://${window.location.host}/rsocket`,
> ```

url: `ws://${window.location.host}:{port}/rsocket`,
i think that you need insert ws's port to url

**Comment by SentryMan** [comment]
I use wss so I don't think thats the issue

**Comment by baudiachatb** [comment]
> I use wss so I don't think thats the issue

i'm getting same issue when using composite metadata but no problem with Seber's issue

**Comment by bseber** [comment]
@baudiachatb indeed, `window.location.host` includes the port. in my example app that would be `8080`. however using the hard coded `"ws://localhost:7000/rsocket"` url still doesn't work.

did you checkout my example project? or do you have a working example? would be nice if this "just works" and I just have a stupid error on my side :-)

**Comment by derTobsch** [comment]
Is this the same behaviour in this stackoverflow entry ? https://stackoverflow.com/questions/63225352/connectmapping-not-getting-triggered-even-after-sending-setup-frame-from-rsocke

**Comment by derTobsch** [comment]
> > I use wss so I don't think thats the issue
> 
> i'm getting same issue when using composite metadata but no problem with Seber's issue

Did you use the code from @bseber exactly as he posted it? If not can you post your code here? Maybe we were missing a little piece.

**Comment by Polve** [comment]
Any news about this problem? Maybe it must be opened on the spring project?

**Comment by viglucci** [comment]
Hi all,

The issue here is a few things:

- It's best to use composite metadata when defining a route
- When using composite metadata, its important to use `IdentitySerializer` for `metadata`

`IdentitySerializer` will pass the value of `metadata` through as-is, without any modification. This is important as the value for `metadata` is already encoded as it should be from `encodeCompositeMetadata(...)`.

Please see https://github.com/bseber/spring-boot-rsocket-example/pull/1/files for example changes.

**Comment by bseber** [comment]
nice, thanks @viglucci!
