### ISSUE TITLE
Doesn't support Channels

### ISSUE THREAD

**Issue by kbahr** [rsocket/rsocket-js#14]
Currently the RSocket implementation does not support requestChannel.

**Comment by kbahr** [comment]
I'm going to start looking at this. We have several use cases for it at Netifi so this is quickly becoming a blocker.

**Comment by kbahr** [comment]
I have a branch that works but I don't have authority to push it to this repo - do I need to fork and link from there or something?

**Comment by lexs** [comment]
@kbahr Yeah please fork and submit a PR. I'm on vacation next week but @josephsavona might have time to take a look before that.

**Comment by kbahr** [comment]
I hope you had a good vacation @lexs . *Poke* you and @josephsavona :)

**Comment by kbahr** [comment]
What's the release process for you guys? I'm definitely eager to start integrating with this.

**Comment by lexs** [comment]
@kbahr It's pretty ad-hoc, I'll make a release tomorrow for you.

**Comment by kbahr** [comment]
Thanks very much, @lexs!

**Comment by lexs** [comment]
@kbahr I tested the new code (yours + a few commits) and ran into issues caused by https://github.com/rsocket/rsocket-js/commit/8441b584492c6877b30043824cdc3b89fbbeb118. We'll see if we can fix this on Monday or if we have to revert. So no release for now. I'll update you on Monday.

**Comment by kbahr** [comment]
Thanks for the heads up, @lexs. Also, there was a change merged to add a
TLS client - is that included in the changes you plan to release?

**Comment by kbahr** [comment]
@lexs any update on this? We're hung up waiting on the TLS and Channels support. Also it would probably be productive to have a face to face meeting at some point since we plan to make heavy use (and contribute back) to this project.

**Comment by lexs** [comment]
@kbahr Found the problem and fixed, just published 0.0.9 with the latest master (which will get pushed as soon as the code fully lands).

I'm in MPK/SF next week so timezones align if you want set something up. Let me know what time works over email.

**Comment by lexs** [comment]
@kbahr Didn't receive any email :O, can you send it to blom@ fb.com?

**Comment by kbahr** [comment]
Ah indeed, my mail client barfed - I've sent it to your FB email now.
