### ISSUE TITLE
[rsocket-adapter-rxjs] RxRequestersFactory.requestChannel - Second send data always ignored by the rsocket server

### ISSUE THREAD

**Issue by Florian935** [rsocket/rsocket-js#234]
## Expected Behavior
When I call:
```javascript
requester
                    .route('request.channel')
                    .request(
                        RxRequestersFactory.requestChannel(
                            of('1', '2', '3', '4', '5'),
                            this._stringCodec,
                            this._stringCodec,
                            5
                        )
                    ).subscribe((response) => console.log(response));
```
I want to see in the console:
```
1
2
3
4
5
```

## Actual Behavior
When I call:
```javascript
requester
                    .route('request.channel')
                    .request(
                        RxRequestersFactory.requestChannel(
                            of('1', '2', '3', '4', '5'),
                            this._stringCodec,
                            this._stringCodec,
                            5
                        )
                    ).subscribe((response) => console.log(response));
```
My console print:
```
1
3
4
5
```
It seems that no matter what data stream you provide to the method, the ```second``` value is always ignored.

## Steps to Reproduce
My RSocket server is written with Spring boot and my frontend is written in Angular You can retrieve my example by following this link: https://github.com/Florian935/rsocket-js-v1-alpha-client-server

```client package Angular``` contains the rsocket-js demo with rxjs adapter and ```server package Spring Boot``` contains the rsocket server.
You can clone this repo and launch in local the client and server.
When front is live, open your browser console and navigate to "Request Channel" button. You will see in the console that only "1, 3, 4, 5" is printed. (the second value is always ignored).

## Possible Solution

When I look at log of the rsocket server, I can see that the first call make a request(1) and then a request(4) (which is corresponding to the prefetch RxRequestersFactory.requestChannel() arguments ?).
We can see that only ```1, 3, 4 and 5``` are passed in the ```onNext()``` method.

![Capture](https://user-images.githubusercontent.com/51712385/176548910-51bb114e-0e4c-471b-b0bd-b577df8298c6.PNG)

I think that this first request(1) is the possible problem and it's perhaps related to this code:

https://github.com/rsocket/rsocket-js/blob/c6d6c4712fc137e3f1c5e5f9105936cdef83e5ca/packages/rsocket-adapter-rxjs/src/Requesters.ts#L133-L159

## Your Environment

Rsocket version used (Frontend: Angular 14):
```
"rsocket-adapter-rxjs": "^1.0.0-alpha.1",
"rsocket-composite-metadata": "^1.0.0-alpha.1",
"rsocket-core": "^1.0.0-alpha.1",
"rsocket-messaging": "^1.0.0-alpha.1",
"rsocket-tcp-client": "^1.0.0-alpha.1",
"rsocket-websocket-client": "^1.0.0-alpha.1",
"rxjs": "~7.5.0"
```

Backend Spring Boot 2.7.1:
````
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-rsocket</artifactId>
</dependency>
```

**Comment by shareisall** [comment]
Same as my case.

**Comment by shareisall** [comment]
File: ObserverToBufferingRSocketSubscriber.tx
Line: 120
Code: const next = this.shift();
Effect: It will remove the first value of the second observable.

**Comment by shareisall** [comment]
Maybe it is a bug of rxjs,  two subject from one partition when join in one observable, the second one will lose the  first value.

**Comment by shareisall** [comment]
It should be a rxjs bug. Check the code snippet below:

```
const values$ = of(0, 1, 2, 3, 4, 5)
const [firstValue$, restValues$] = partition(
    values$.pipe(
        share({
            connector: () => new Subject(),
            resetOnRefCountZero: true
        })
    ),
    (index, _index) => index === 0
)

firstValue$
    .pipe(
        tap(() => restValue$.subscribe(r => console.log(r))),
        take(1)
    )
    .subscribe(r => console.log(r))

2    // 2 of restValues, but 1 of restValues has lose.
3    // 3 of restValues
4    // 4 of restValues
5    // 5 of restValues
0    // 0 of fistValue
```

**Comment by Florian935** [comment]
Hi.

Nice debug, you found thé Root bug good job !!
Non we have to wait the fix to use the requestChannel interaction with rxjs
adapter packages ...
Perhaps you can post the bug of rxjs in comment of the issue ?

Have a good day !

Le jeu. 7 juil. 2022 à 08:27, shareisall ***@***.***> a
écrit :

**Comment by shareisall** [comment]
It should be a rxjs bug. Check the code blow:

```
const values$ = of(0, 1, 2, 3, 4, 5)
const [firstValue$, restValues$] = partition(
    values$.pipe(
        share({
            connector: () => new Subject(),
            resetOnRefCountZero: true
        })
    ),
    (value, index) => index === 0
)

firstValue$
    .pipe(
        tap(() => restValue$.subscribe(r => console.log(r))),
        take(1)
    )
    .subscribe(r => console.log(r))

2    // 2 of restValues, but 1 of restValues has gone.
3    // 3 of restValues
4    // 4 of restValues
5    // 5 of restValues
0    // 0 of fistValue
```


How to fix: DO NOT share the source observable to subject.

```
const values$ = of(0, 1, 2, 3, 4, 5)
const [firstValue$, restValues$] = partition(
    values$,
    (value, index) => index === 0
)

firstValue$
    .pipe(
        tap(() => restValue$.subscribe(r => console.log(r))),
        take(1)
    )
    .subscribe(r => console.log(r))
```
result:
1    // 1 of restValues
2    // 2 of restValues
3    // 3 of restValues
4    // 4 of restValues
5    // 5 of restValues
0    // 0 of firstValues

**Comment by shareisall** [comment]
So we can delete the compiled code of file Requesters.ts to fix it:
file path: YOUR_PROJECT/node_modules/rsocket-adapter-rxjs/Requesters.ts
code begin line 81 to 84:
```
    var _a = __read((0, rxjs_1.partition)(datas.pipe((0, rxjs_1.share)({
        connector: function () { return new rxjs_1.Subject(); },
        resetOnRefCountZero: true,
    })), function (_value, index) { return index === 0; }), 2), firstValueObservable = _a[0], restValuestObservable = _a[1];
```
modify to:
```
    var _a = __read((0, rxjs_1.partition)(datas.pipe(
        // (0, rxjs_1.share)({
        //     connector: function () { return new rxjs_1.Subject(); }, 
        //     resetOnRefCountZero: true,
        // })
    ), function (_value, index) { return index === 0; }), 2), firstValueObservable = _a[0], restValuestObservable = _a[1];
```

**Comment by tukez** [comment]
I have the same problem, second message is missing on the client->server stream.

About the possible solution, I believe the prefetch-parameter affects the server->client stream, not the client->server stream. On my setup I have unbounded requests on the server side (requesting the client->server stream, Spring Boot server).
