### ISSUE TITLE
reactor-core-js project to re-open

### ISSUE THREAD

**Issue by maxim-bandurko-lsvt** [rsocket/rsocket-js#247]
Ref to: https://github.com/reactor/reactor-core/issues/3178

This issue is kind off topic for Reactor Core Java, but there are no way to post it to https://github.com/spring-attic/reactor-core-js as those repository is archived.

@simonbasle I have a very draft version of Reactor Core built in TypeScript (oriented for browser) that has exact copy of Java version logic (basically, taking .java file and adopting the code to TypeScript/JavaScript). The goal was to have as less as possible changes of original Java code, so it was implemented a way to support in TypeScript certain things that Java has (like Functional Interface, interfaces implementations, super in type, recursive dependency injection, etc). For that have light version of Java JDK in TypeScript that allows just convert the Java code logic to TypeScript syntax and in future easily keep in sync the TypeScript version of project with Java version. Library built using the Java source of Reactor Core 3.4, but could be updated to follow v3.5 in future.

So, proposing the idea to open the repository if somebody is interested in JS version of Reactor Core (especially direction of using it inside Front End that works with RSocket), as it brings can say "native" Flux and Mono from Java world to JS.

**Comment by maxim-bandurko-lsvt** [comment]
@OlegDokuka What kind of adjustment can be if we will have it under rsocket?

**Comment by OlegDokuka** [comment]
@maxim-bandurko-lsvt how about scheduling a call and discussing that in voice?

**Comment by maxim-bandurko-lsvt** [comment]
@OlegDokuka sure. How can I contact to you to give my contacts?
