### ISSUE TITLE
There are few explanatory documents, which are too difficult to use.

### ISSUE THREAD

**Issue by mmm8955405** [rsocket/rsocket-js#266]
## Steps to Reproduce

```java
@Test
public void reproCase() {

}
```

## Your Environment

* RSocket version(s) used:
* Other relevant libraries versions (eg. `netty`, ...):
* Platform (eg. JVM version (`javar -version`) or Node version (`node --version`)):
* OS and version (eg `uname -a`):

**Comment by viglucci** [comment]
@mmm8955405 which version are you working with? `0.0.27` or the newer `1.0-alpha`?

I am very happy to improve the documentation -- but also it would be appreciate if you could take the time to provide more information and fill out the issues template with more details.
