### ISSUE TITLE
Resumable transport: switch to byte-count for position tracking

### ISSUE THREAD

**Issue by mostroverkhov** [rsocket/rsocket-js#30]
Hello,
atm js and c++ implementations treat resumable position differently - frame position vs byte count. Recently byte-count based resumption was added to RSocket-java, and I am wondering if It makes sense to switch RSocket-js to byte-count too, so all 3 interact nicely with each other. Some initial work of mine is available at https://github.com/mostroverkhov/rsocket-js/tree/fix-resume

**Comment by robertroeser** [comment]
@lexs @lehecka any thoughts about this issue?

**Comment by josephsavona** [comment]
I looked at this when implementing it. The main limitation of byte-count-based resumption is that it means the resumption logic has to operate at the level of encoded frames, which limits implementation flexibility. The current rsocket-js resumption implementation is transport and encoding agnostic which is a pretty nice property to have.

**Comment by robertroeser** [comment]
The specification is byte-count-based - this need to get changed to match the specification, and this doesn't work with C++ or Java, so it's not very useful. It should be update to the 1.0 spec.

**Comment by josephsavona** [comment]
Yes, I’m aware. Just pointing it out since the choice was largely arbitrary and if it’s possible to change the spec, it may still be beneficial to do so. (Note that the version of the spec that I implemented the version here against was ambiguous as to byte/position based counts).

**Comment by robertroeser** [comment]
We cleared up the byte-counting in the protocol, and the Java and C++ work by counting bytes.

**Comment by robertroeser** [comment]
@josephsavona  @lexs  - we'd like to move start moving forward updating Javascript to match the protocol, Java, and C++

**Comment by mostroverkhov** [comment]
closed by https://github.com/rsocket/rsocket-js/pull/38
