### ISSUE TITLE
Does RSocket in general, and RSocket-JS specifically, support UDP?

### ISSUE THREAD

**Issue by trusktr** [rsocket/rsocket-js#31]
I looked in the main doc repo, but I only saw [one reference to "UDP"](https://github.com/rsocket/rsocket/search?utf8=%E2%9C%93&q=udp&type=. ), and [zero references to "UDP"](https://github.com/rsocket/rsocket-js/search?q=udp&unscoped_q=udp) in this rsocket-js repo.

I'm interested to know both if there's a UDP-based RSocket implementation in general, and if there's anything for JS specifically.

Also, maybe I'm misunderstanding, is RSocket something that you wouldn't want over UDP?

**Comment by trusktr** [comment]
Ah, okay, I see Aeron protocol is supported. Is there support for this in JS yet (Node.js)?

**Comment by OlegDokuka** [comment]
Hey. There is no implementation of the aeron so far.
