### ISSUE TITLE
React Native+Proteus JS,WebSocket will not automatically reconnect to Proteus Broker

### ISSUE THREAD

**Issue by yangjun** [rsocket/rsocket-js#32]
https://github.com/netifi-proteus/proteus-js/issues/27

**Comment by yangjun** [comment]
@lexs

**Comment by robertroeser** [comment]
not related to rsocket-js - please followup with Duncan here - https://community.netifi.com/t/react-native-proteus-js-websocket-will-not-automatically-reconnect-to-proteus-broker/132/9

Thanks,
Robert
