### ISSUE TITLE
Mistake in the Client Configuration doc

### ISSUE THREAD

**Issue by raphael-jungers** [rsocket/rsocket-js#33]
I think there's a mistake in the browser example of the Client configuration documentation : 

`  transport: new RSocketWebSocketClient({uri: 'wss://...'}),`

should be 

`  transport: new RSocketWebSocketClient({url: 'wss://...'}),`

When using "uri" I get this message: "An invalid or illegal string was specified", but using "url" fixed it.

**Comment by yschimke** [comment]
Thanks, fixed.
