### ISSUE TITLE
TypeScript type definitions

### ISSUE THREAD

**Issue by adrianhopebailie** [rsocket/rsocket-js#34]
I have pulled together type definitions for this project at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36076

However I could use some help resolving the issue with `Partial<T>` so they can be merged.

**Comment by robertroeser** [comment]
@OlegDokuka or @kbahr might be able to help

**Comment by OlegDokuka** [comment]
I have one. Will send a PR

**Comment by OlegDokuka** [comment]
Will take a look at that

**Comment by OlegDokuka** [comment]
@adrianhopebailie looks like you have got a chance to fix that. Do you need any other help?

**Comment by adrianhopebailie** [comment]
No, think I have them all done now. Was a mistake on my part in the definition of `map()` for the FlowableProcessor.

If anyone is using TypeScript I'd appreciate any feedback on whether those types work as expected. 

I built them so I can use them to learn rsocket so might be a while before I pick up any nuanced issues if there are any.

**Comment by adrianhopebailie** [comment]
Will post here and close the issue when the definitions are published at DefinitelyTyped

**Comment by adrianhopebailie** [comment]
Merged: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36076
