### ISSUE TITLE
RSocketClient: Cannot issue request, maximum stream id reached (2147483647).

### ISSUE THREAD

**Issue by Lellansin** [rsocket/rsocket-js#40]
Our project meet the `RSocketClient: Cannot issue request, maximum stream id reached (2147483647).` in production.

And we get a little confused about, that it's said it should auto reconnect or re-use the  stream id in [protocol](http://rsocket.io/docs/Protocol#stream-identifiers) but rsocket-js client did nothing but throw error.

- Should the reconnection occurs in business logic layer?
- Is the stream id re-use action in TODO list? We'd like to PR for our project. But, we got a rsocket server in Java version, it seems like this feature need both Java & Js version update?

BTW, Java version didn't throw error while stream id approach `2^31 - 1` (check [this Java code](https://github.com/rsocket/rsocket-java/blob/21c39bdaa60c6a916e3288048b268f2b756dd5e7/rsocket-core/src/main/java/io/rsocket/StreamIdSupplier.java#L40))

**Comment by xiazuojie** [comment]
It's actually quite easy to reach maximum stream id (2147483647):
Without considering keep-alive requests, for a 1000 qps connection, it only takes 24.85 days to reach maximum stream id.
2147483647 / 24 / 60 / 60 / 1000 = 24.85 days

**Comment by xiazuojie** [comment]
Instead of all the fuss about re-use, why not simply use 64 bit? As stated above, 32 bit is, practically speaking, very likely to reach in our user case.

**Comment by Lellansin** [comment]
> Instead of all the fuss about re-use, why not simply use 64 bit? As stated above, practically speaking, our user case is very likely to reach 32 bit's limit.

According to the [protocol](http://rsocket.io/docs/Protocol#frame-header-format), the stream id only got 32bit.

**Comment by xiazuojie** [comment]
> 
> According to the [protocol](http://rsocket.io/docs/Protocol#frame-header-format), the stream id only got 32 bits.

I was suggesting a change of protocol.

**Comment by linux-china** [comment]
RSocket Java solution for stream id overflow and reuse:  https://github.com/rsocket/rsocket-java/blob/develop/rsocket-core/src/main/java/io/rsocket/StreamIdSupplier.java
