### ISSUE TITLE
How to run the examples?

### ISSUE THREAD

**Issue by haalcala** [rsocket/rsocket-js#50]
Sorry for the dumb question, but I really need your help on this.

Thank you in advance.

**Comment by haalcala** [comment]
Sorry. I managed to figure it out. I just couldn't imagine how a simple javascript sample project can become so complicated. :(

**Comment by fjacobs** [comment]
How were you able to do it?

**Comment by fjacobs** [comment]
For anyone who can't figure it out.

1. Install yarn in your OS.
2. Go to the root directory of this project
3. Type 'yarn install' in CLI
4. Type 'yarn run' in CLI
5. Then the CLI will output the examples that can be run. (Or instead of step 4. you can do yarn run simple-cli for example)
