### ISSUE TITLE
rsocket-core 0.0.10 does not allow data or metadata in setup frame

### ISSUE THREAD

**Issue by mmihael** [rsocket/rsocket-js#51]
I'm not able to set data or metadata in the setup frame with rsocket-core 0.0.10.
Checking on the master branch and this has been enabled in the meantime but still not released with a new version on npm.

Is there any release plan scheduled or we need to use sources directly to have this functionality?

**Comment by OlegDokuka** [comment]
https://github.com/rsocket/rsocket-js/pull/46

**Comment by mmihael** [comment]
That is true, but issue is that there is no npm package version with that changes.

**Comment by robertroeser** [comment]
@mmihael we'll be releasing an npm package shortly

**Comment by afuentes** [comment]
Hi  @robertroeser  do you have any update about npm package release date.
