### ISSUE TITLE
Request Channel implementation

### ISSUE THREAD

**Issue by maxim-bandurko-lsvt** [rsocket/rsocket-js#52]
Hello.

Is it possible to have the requestChannel be implemented? As it comes to point, that rsocket can be used only in Java world mostly (in applications that do not need to deal with websockets). But when it comes to Javascript (client) <-> Java (server) over the websokets, this combination is limited, and requires to use a tricks with requestStream to achieve the similar behavior as requestChannel brings. And that in some kind stops the massive usage of rscoket over the websocket in Javascript world.

Thank you.

**Comment by OlegDokuka** [comment]
Hi @maxim-bandurko-lsvt!

What kind of issues prevents the usage of requestChannel! Up to my knowledge and the sourcecode -> https://github.com/rsocket/rsocket-js/blob/master/packages/rsocket-core/src/RSocketMachine.js#L373 

it should just work. 

Let me know if there are particular limitations.

Regards,
Oleh

**Comment by maxim-bandurko-lsvt** [comment]
Hello Oleg @OlegDokuka !

Getting message that it is not implemented when doing requestChanel at javascript client.

Also, the same told at: https://github.com/rsocket/rsocket-js/blob/master/docs/02-client-api.md

Regards,
Max

**Comment by OlegDokuka** [comment]
Ah... The docks is lying. Let us prepare a working sample for yoy

**Comment by maxim-bandurko-lsvt** [comment]
@OlegDokuka Thank you!

**Comment by hypothete** [comment]
Hi Max,
Here's [a gist](https://gist.github.com/hypothete/234c981988f1800c118e682dbda462bb) from a working implementation of channels in JS between a Node server and a client on the frontend. Please take a look and let us know if you have any questions. Thanks!

**Comment by yosiat** [comment]
Hi!

I can't get the `requestChannel` to work here, the client is in nodejs and server in java.
This is my code:

```
  client.socket
    .requestChannel(
      Flowable.just({
        data: data
      })
    )
    .subscribe({
      onComplete: function() {
        console.log("completed", arguments);
      },

      onError: function(err) {
        console.log("err", arguments);
      },

      onNext: function(data) {
        console.log("next", data);
      },

      onSubscribe: function(subscription) {
        console.log("got subscription");
        subscription.request(1);
      }
    });
```

and on the server as soon as I get subscription I am publishing to the subscriber and I not getting the `onNext` log call

BTW - this protocol and libraries are really helping to me improve performance of the current application, but the lack of documentation in both js & java land make it's really hard to use.

**Comment by hypothete** [comment]
Hi @yosiat, I'm putting together an example for you with a Node client and server, and should have it ready tomorrow. Can you share your request handler from your server?

**Comment by yosiat** [comment]
@hypothete found my issue - was on the java side (https://github.com/rsocket/rsocket-java/issues/675).

I am waiting for the example, to understand more about rsocket-js, there some things that miss documentation and I have hard time using:
* `request` on subscription - I want requestChannel to behave like websocket, so should I pass `request(MAX_INTEGER_VALUE)` ?
* I am not sure how to create Flowable and pass information to it for `requestChannel` (btw, what is the difference between flowable and rxjs Observable) ?

**Comment by hypothete** [comment]
@yosiat I'm glad you spotted the issue! In the meantime, I put together an example which you can check out [here](https://github.com/netifi/rsocketjs-channel-demo). To be clear, there's some flexibility around how and when you want your client and server responding to each other, this is just one way to do it.

In the example, I have the client request the max number it can handle (currently 0x7fffffff for the JS implementation) from the server. The server however responds to JS requests, so I have it calling subscription.request(1) in onSubscribe and also in onNext. Depending on your application you might want to manage it differently.

Flowables and Singles are basically ReactiveStream Publishers. You can read about how they work [here](https://github.com/rsocket/rsocket-js/blob/master/docs/03-flowable-api.md). It's possible to wrap both classes in RxJS Observables, and we use [our converter](https://github.com/netifi/netifi-js-client/blob/master/src/rx/FlowableAdapter.js) extensively in JS development at Netifi.

I hope this answers your questions!

**Comment by maxim-bandurko-lsvt** [comment]
@hypothete Have a question on requestChannel. Is there a way to track each requestChannel procedures? Like having requestChannel executed one time and binded "onNext" and after that need several more channels be requested, but need to bind to another callback at "onNext"? As every time doing request channel, all new binded responses got executed with all previous ones. 

`socket.requestChannel(Flowable.just(...clientRequests))
    .subscribe({
      onSubscribe: sub => {
        subscription = sub;
        console.log(`Client is establishing a channel 1`);
        subscription.request(0x7fffffff);
      },
      onNext: response => {
        console.log("channel 1", response);
      },
      onComplete: () => {
        console.log(`Client received end of server stream`);
      }
    });

socket.requestChannel(Flowable.just(...clientRequests))
    .subscribe({
      onSubscribe: sub => {
        subscription = sub;
        console.log(`Client is establishing a channel 2`);
        subscription.request(0x7fffffff);
      },
      onNext: response => {
        console.log("channel 2", response);
      },
      onComplete: () => {
        console.log(`Client received end of server stream`);
      }
    });`

The same behavior happens actually with requestStream also.

**Comment by hypothete** [comment]
@maxim-bandurko-lsvt Let me see if I understand - you would like responses from the server to not be repeated when you start more than one requestChannel? You should be able to do that on the server side by managing the scope where your responses are defined. Here I've moved the responses array to the top scope in the server, and since I'm calling `subscriber.onNext(responses.shift())` the array is mutated with each onNext():

```
let responses = ['g', 'h', 'i'];
responses = responses.map(res => {
  return {
    data: res
  };
});

const getRequestHandler = () => { // etc.
```

The resulting log with a client setup like your example:
```
$ node client.js
Client connected to the RSocket server
Client is establishing a channel
Client is establishing a channel
channel 1: g
channel 2: h
channel 1: i
Channel 1 received end of server stream
Channel 2 received end of server stream
```

**Comment by maxim-bandurko-lsvt** [comment]
@hypothete Probably I wasn't able to explain better the situation or may be I am not understanding something in right way. So, let me explain with more details.

Having ws client that I want to use all benefits of reactive streams. My understanding of streams model client <-> server is that streams should be independent. Similar to streams inside server. Client can subscribe to certain streams and has to be able to sync received streams data from server. Like use case example, we have streams "A" and "B" publisher at server. JS client side also has streams "A" and "B". Client is doing subscribe to stream "A" to server, and after some time doing one more subscribe to stream "B". So, we got 2 subscriptions to different streams. Once server emits stream data at stream "A", client has to get this data and publish inside JS stream "A". Similar with stream "B". Once JS client got data published at some certain stream, everything else inside JS goes with all reactive streams way inside API.

So, issue is that when I am having requestStream inside JS client with stream id in metadata (stream "A"), response of published stream data from server got to binded "onNext". But, when I need to request one more stream and passing stream id in metadata at this request (stream "B"), and also having another binded listener for exactly this stream "B" request, when server emits any stream, both binds got the response. 

Probably, my question is, may be it is supposed to be so? Client can do requestStream only one time and bind the response handler that will work as a publisher for streams inside JS and all logic of transformation of this one global stream (server -> client) of splitting it into multiple streams by certain conditions, for example by id, should be handled in my api?

**Comment by maxim-bandurko-lsvt** [comment]
@hypothete Or may be coming the result output in your reply, you have one stream and multiple channels. Certain stream is got propagated to certain channel binder (channel 1, channel 2). I wasn't able to find any examples of how to get the simple subscription to certain channel working with subscription to stream.

Like in most JS client apis, we need to have subscription to certain channels, and certain channel streams once got data exactly for this channel, has to be propagated to all stream binds. 

Example, simple chat. Have 2 channels "group 1" and "group 2". Have a requestChannel be subscribed to both groups. Once server got data for group 1, JS client has to get this data. If group 2 - JS client get data for group 2.

**Comment by viglucci** [comment]
> Ah... The doc is lying. Let us prepare a working sample for you

PR (https://github.com/rsocket/rsocket-js/pull/54) submitted with a proposed amendment to the documentation.

**Comment by hypothete** [comment]
@maxim-bandurko-lsvt I [made a branch](https://github.com/netifi/rsocketjs-channel-demo/tree/separate-channels) of the demo I posted on here last week, maybe this gets closer to the implementation you are looking for? The server identifies the client based on client metadata, and searches an array of responses for the appropriate response with each request. Ultimately it is the responsibility of the service to keep track of its clients.

**Comment by maxim-bandurko-lsvt** [comment]
@hypothete Thank you! Your example very close to implementation and works perfect ;)

Have one more question, it is not connected with this ticket, but, is there a way to have server be able to make requestChannel and requestStream to client?

**Comment by maxim-bandurko-lsvt** [comment]
Situation when it is needed is when client has to stream a lot of data. At current moment only way is fireAndForget method from client to server. It would be convenient to have a requested stream or channel from client.

**Comment by hypothete** [comment]
@maxim-bandurko-lsvt There's not explicitly a relationship like you describe defined in the spec. One way to do this would be to use requestChannel, and have the server respond once at the beginning or the end of the client stream.

**Comment by maxim-bandurko-lsvt** [comment]
@hypothete I understand. Thing is that requestChannel in this situation will be executed too often, like example every 300ms, as client stream data will be growing constantly and using it client has to push the stream data batches to server constantly (ideally would be pushing at each onNext). That is why having reverse logic of request from server to client can be very beneficial. May be I need to create new issue ticket on this?

**Comment by mostroverkhov** [comment]
@maxim-bandurko-lsvt RSocket is symmetric and supports all 4 interaction models (including stream and channel) originating from server to client once connection is established. rsocket-js implements this, showcased in leases demo at https://github.com/rsocket/rsocket-js/blob/a2e6c776640c523a5f04023ed176e202adada24e/packages/rsocket-examples/src/LeaseClientExample.js#L104

**Comment by mostroverkhov** [comment]
@maxim-bandurko-lsvt RSocket is symmetric and supports all 4 interaction models (including stream and channel) originating from server to client once connection is established, rsocket-js implements this, showcased in leases demo at https://github.com/rsocket/rsocket-js/blob/a2e6c776640c523a5f04023ed176e202adada24e/packages/rsocket-examples/src/LeaseClientExample.js#L104

**Comment by maxim-bandurko-lsvt** [comment]
@mostroverkhov Nice! But, how to originate this requestChannel from server to client? I was trying to find some examples on doing this, but it is lack of documentation.

**Comment by maxim-bandurko-lsvt** [comment]
@mostroverkhov Forgot to mention, that I am having the server in Java and client in Javascript, and transport is over the websockets. So trigger to originate requestStream or requestChannel from server to client is fireAndForget from client to server.

**Comment by recoilRamires** [comment]
Could someone provide an example of how to stop the 'Request_Channel' from being canceled or completed? What I mean by that is the following behavior: 

When I send such a request from the client, the server debug mode shows this:

: receiving -> 
Frame => Stream ID: 5 Type: REQUEST_CHANNEL Flags: 0b100000000 Length: 26
Metadata: /a frame with info/
Data: /a frame with info/

: sending -> 
Frame => Stream ID: 5 Type: REQUEST_N Flags: 0b0 Length: 10
Data: /empty here/

: sending -> 
Frame => Stream ID: 5 Type: REQUEST_N Flags: 0b0 Length: 10
Data: /empty here/

: sending -> 
Frame => Stream ID: 5 Type: NEXT Flags: 0b100000 Length: 138
Data: /the frame for it with info/

: sending -> 
Frame => Stream ID: 5 Type: NEXT Flags: 0b100000 Length: 135
Data: /the frame for it with info/

: sending -> 
Frame => Stream ID: 5 Type: CANCEL Flags: 0b0 Length: 6
Data: /empty again/

: sending -> 
Frame => Stream ID: 5 Type: COMPLETE Flags: 0b1000000 Length: 6
Data: /empty/

As you can see the server is sending the COMPLETE flag, and I want to prevent it. How can I do it. It is a spring boot server. 

I had the same issue on the client part, but after a look in the js implementation I could just provide a custom Flowable like:

socket.requestChannel(
               // a Flowable with own 'request' function implementation in the subscriber
).subscribe();

-> so that nothing else sets the COMPLETE flag from the client part. (This is a workaround I believe, so what is the actual way of doing it?. Again this is on the client)

..............................
Can you explain better how we have control over those flags. 
In docs it is stated:
(C)omplete: bit to indicate stream completion.
If set, onComplete() or equivalent will be invoked on Subscriber/Observer.

Where and how we set it?

I am really struggling to get better understanding on the protocol, will highly appreciate if somebody write an example or description. What I try to achieve is to have an open channel between client and server, only close on particular condition. 

And I would also like to know how to trigger this channel effects from another event happening on server. Imagine, we have 3 different clients 'subscribed' on this channel. If a new client sends data to '/join', but '/join' is mapped to 'request-response' controller, how 'request-response' can trigger 'request-channel' and notify all 3 subscribed clients? Is it possible ?

I am sorry if the answers of those questions are already posted somewhere. But I find docs unclear for some particular things. Also maybe we should collect all the answers in a single place such as FAQ sections, instead of being so scattered.

Meanwhile I will keep on trying different approaches here and there. Thank you for your time, awesome work so far.

**Comment by sameerasaad** [comment]
HI, is there document on how to originate request using requestChannel or any other interaction from server to client? i have Java server and Javascript client 
@maxim-bandurko-lsvt  i saw you were asking for the same did you have any document on how to do that ?

**Comment by maxim-bandurko-lsvt** [comment]
@sameerasaad Honestly - no, I haven't time to work with that, but can point you to direction from what to start - on Java server side, you need to get the exact rsocket request socket and do requestChannel to it. 

Indeed, I think that such situation happens too seldom that server has to initialize requestChannel, but very fast work around on how to skip the server side digging, you can just do requestStream from front end and store those client stream reference on server side. Frontend handler can just subscribe to this requestStream and listen for commands from server. Server can publish to front end something like action: 1, route: "some.route" and front end will do this action for this route. Dirty, but very fast solution. And maybe, even make sense from backpressure side, as front end will still be available to control the data publishing flow that server requested. The only thing is that with this variant, server can't control the flow, but, server always can send new command like "close" to close channel or "pause" if needed to pause.

**Comment by markathomas** [comment]
@hypothete I have a rsocket java server running a channel secured using JWT that responds correctly to the rsc cmd line app but I and others on the team are struggling to get a javascript client working.  The rsc line is as follows:

`rsc --ab 'MY_JWT_ACCESS_TOKEN' --channel -d '{"action":"load","symbols":["SPLK","CSCO"]}' -r iex --debug ws://localhost:7000/ws --stacktrace`

Any help is much appreciated!

**Comment by OlegDokuka** [comment]
@markathomas can you please explain in more detail what you are struggling with? Any code samples to share? 

Also, have you seen a [CompositeMetadataExample](https://github.com/rsocket/rsocket-js/blob/master/packages/rsocket-examples/src/CompositeMetadataExample.js) which demonstrates the usage of composite metadata?

Finally, we have a request channel properly working, please find an example bellow: 

```
rsocket.requestChannel(new rsocketFlowable.Flowable(source => {
                console.log("channel")
                source.onSubscribe({
                    cancel: () => {},
                    request: (n) => {}
                })
                messageButton.on("click", function() {
                    var content = messageInput.val();
                    messageInput.val("");
                    if (content) {
                        source.onNext({
                            data: Buffer.from(JSON.stringify({content: content , user: user, sent: new Date().toISOString()})),
                            metadata: encodeCompositeMetadata([
                              [MESSAGE_RSOCKET_ROUTING, encodeRoute('iex')],
				              [
				                  MESSAGE_RSOCKET_AUTHENTICATION,
				                  encodeBearerAuthMetadata('MY_JWT_ACCESS_TOKEN'),
				              ],
				              ['action', Buffer.from('load')],
				              ['symbols', Buffer.from("[SPLK, CSCO]"])],
				            ]),
                        });
                    }
                });
            }))
                .subscribe({
                    onSubscribe: (s) => {
                        s.request(1000)
                    }
                });
```

**Comment by markathomas** [comment]
@OlegDokuka thank you for your example.  What we are seeing is a handshake completing but a connection never being fully established.  Using your example, a request is never made to the backend to authenticate.  Here's what I'm using:

```
import RSocketWebSocketClient from "rsocket-websocket-client";
import {BufferEncoders, MESSAGE_RSOCKET_COMPOSITE_METADATA, RSocketClient,} from "rsocket-core";
import {useState} from "react";
import {
    encodeBearerAuthMetadata,
    encodeCompositeMetadata,
    encodeRoute,
    JsonSerializer,
    MESSAGE_RSOCKET_AUTHENTICATION,
    MESSAGE_RSOCKET_ROUTING
} from "rsocket-core/build";
import {Flowable} from "rsocket-flowable/build";

const wsUrl = "ws://localhost:7000/ws";
const randomJwt = "RANDOM";
const channelRoute = "iex";

function Test() {
  const [client, setClient] = useState(null);
  const [socket, setSocket] = useState(null);

  const [msgCompositeChannel, setMsgCompositeChannel] = useState("");

    function compositeChannelRequest(socket, callback) {

        socket.requestChannel(new Flowable(source => {
            console.log("channel")
            source.onSubscribe({
                cancel: () => { },
                request: (n) => {
                    callback(n);
                }
            })

            source.onNext({
                data: Buffer.from(JSON.stringify({"action":"load","symbols":["SPLK","CSCO"]})),
                metadata: encodeCompositeMetadata([
                    [MESSAGE_RSOCKET_ROUTING, encodeRoute('iex')],
                    [
                        MESSAGE_RSOCKET_AUTHENTICATION,
                        encodeBearerAuthMetadata(randomJwt),
                    ],
                ])
            });
        })).subscribe({
            onSubscribe: (s) => {
                s.request(Number.MAX_SAFE_INTEGER)
            },
            onNext: (s) => {
                callback(s);
            }
        });
    }

  if(client == null) {
    const c = new RSocketClient({
        serializers: {
            data: JsonSerializer,
            metadata: JsonSerializer,
        },
      "setup": {
        "keepAlive": 120000,
        "lifetime": 180000,
        "dataMimeType": "application/json",
        "metadataMimeType": MESSAGE_RSOCKET_COMPOSITE_METADATA.string,
          payload: {
              metadata: encodeCompositeMetadata([
                  [MESSAGE_RSOCKET_AUTHENTICATION, encodeBearerAuthMetadata(randomJwt)],
              ])
          }
      },
      "transport": new RSocketWebSocketClient({
        "url": wsUrl
      }, BufferEncoders)
    });
    setClient(c);
    c.connect().then(
        (socket) => {
          setSocket(socket);
          console.log("composite connection succeeded!");
        },
        (error) => {
          console.log("composite initial connection failed");
        }
    );
    console.log("connecting!");
  }
  if(socket != null && client != null) {
    return <div>
      <button onClick={() => compositeChannelRequest(socket, (msg) => {setMsgCompositeChannel(msg)})}>Composite Channel</button>
      <div>{msgCompositeChannel}</div>
    </div>;
  } else {
    return <div>Connecting!</div>;
  }
}

export default Test;
```

**Comment by markathomas** [comment]
I see data being encoded on the client but on the server it is not present as if it was not sent.  Also, calling `socket.requestChannel(Flowable)` is not making a channel request to the server

**Comment by markathomas** [comment]
@OlegDokuka what i've observed is on the java server the composite metadata is empty despite being set on the client.  Is there any known limitations between this js lib and Spring Boot RSocket Starter + Spring Security?

**Comment by markathomas** [comment]
Here is a working example with Spring Boot RSocket + Spring Security:

```
import RSocketWebSocketClient from "rsocket-websocket-client";
import {BufferEncoders, MESSAGE_RSOCKET_COMPOSITE_METADATA, RSocketClient,} from "rsocket-core";
import {useState} from "react";
import {
    APPLICATION_JSON,
    encodeBearerAuthMetadata,
    encodeCompositeMetadata,
    encodeRoute,
    MESSAGE_RSOCKET_AUTHENTICATION,
    MESSAGE_RSOCKET_ROUTING
} from "rsocket-core/build";
import {Flowable} from "rsocket-flowable/build";

const wsUrl = "ws://localhost:7000/ws";
const randomJwt = "JWT_TOKEN";

function Test() {
    const [client, setClient] = useState(null);
    const [socket, setSocket] = useState(null);

    if(client == null) {
        const c = new RSocketClient({
            setup: {
                keepAlive: 120000,
                lifetime: 180000,
                dataMimeType: APPLICATION_JSON.string,
                metadataMimeType: MESSAGE_RSOCKET_COMPOSITE_METADATA.string
            },
            transport: new RSocketWebSocketClient({
                url: wsUrl,
                debug: true,
            }, BufferEncoders)
        });
        setClient(c);
        c.connect().then(
                (socket) => {
                    setSocket(socket);
                    socket.requestChannel(Flowable.just({
                        data: Buffer.from(JSON.stringify({"action":"load","symbols":["SPLK","CSCO"]})),
                        metadata: encodeCompositeMetadata([
                            [MESSAGE_RSOCKET_ROUTING, encodeRoute('iex')],
                            [MESSAGE_RSOCKET_AUTHENTICATION, encodeBearerAuthMetadata(randomJwt)]
                        ])
                    })).subscribe({
                        onComplete: () => console.log('complete'),
                        onError: error => {
                            if (error && error.source && error.source.code === 513
                                && error.source.message.indexOf('Access token expired') > -1) {
                                // TODO: re-authenticate
                            }
                            console.log(error);
                        },
                        onNext: payload => {
                            const json = payload.data.toString();
                            console.log(json);
                        },
                        onSubscribe: subscription => {
                            subscription.request(2147483647);
                        },
                    });
                    console.log("composite connection succeeded!");
                },
                (error) => {
                    console.log("composite initial connection failed", error);
                }
        );
        console.log("connecting!");
    }
    if(socket != null && client != null) {
        return (<div>Connected - see log!</div>);
    } else {
        return <div>Connecting!</div>;
    }
}

export default Test;
```

**Comment by markathomas** [comment]
@OlegDokuka how, once channel is connected, do you send a message back to the server?

**Comment by bke243** [comment]
@OlegDokuka  is it possible to have an emitter that will be sending messages to server when needed using the same chanel once connect  ?

**Comment by OlegDokuka** [comment]
@bke243 Yeah. I dont see anything that should prevent you from doing that. You may store the link to the outbound observer and send events when needed

**Comment by OlegDokuka** [comment]
Folks. I'm closing this ticket since it started being used as a thread for questions. 

Please feel free to ask your question there -> https://gitter.im/rsocket/rsocket-js

@maxim-bandurko-lsvt feel free to reopen this ticket if you have any other concerns related to the requestChannel scenario

**Comment by maxim-bandurko-lsvt** [comment]
@OlegDokuka I think that those scenario is completely resolved and explained. Thank you!

**Comment by Toso7** [comment]
@OlegDokuka Do you have somewhere example How Can I sending messages to server when needed using the same channel once connect ?
