### ISSUE TITLE
[Question] Open to extending documentation with static site?

### ISSUE THREAD

**Issue by viglucci** [rsocket/rsocket-js#55]
Over the last couple of weeks, I have been evaluating RSocket for a range of use-cases, and while I have been pretty excited about the core concepts, principles, and possibilities, I have also found the documentation and information gathering to be a bit spread between a few different GitHub repositories, and a few websites, and in general have found the 'getting started' experience to be a bit of a learning curve. To combat this, I would like to propose the creation of a static documentation website for this repository, as I believe it would assist with co-locating relative documentation and examples (recipes, etc) that could help increase the prevalence of RSocket consumers in the JS space.

Are the maintainers of this project open to extending the documentation with a statically generated site? I would be interested in exploring opportunities for doing so, however, I would like to gauge the interest of the core maintainers to avoid wasted effort/work.

Generating a static site for documentation purposes could be accomplished by using one of the following tools:

- https://docusaurus.io/en/
- https://docsify.js.org/
- https://www.gatsbyjs.org/

Has any thought gone into how the core maintainers of this project would prefer this be approached?

**Comment by robertroeser** [comment]
I've been having discusses about documentation with various people, and want  to improve the documentation across the ecosystem. Now that the Reactive Foundation is in place we have a mechanism to drive that - now that RSocket has a home. The rsocket.io website uses docusaurus - mainly because it worked okay, and I lack skill as a web developer. Definitely open to better solutions. I really like [How to GraphQL](https://www.howtographql.com/) - I was thinking we could draw inspiration there. What are your thoughts about a 'How to RSocket' Site inspired by the GraphQL one?

**Comment by viglucci** [comment]
I wasn't familiar with the "How to GraphQL" (HTGQL) site until today, however, it looks like a pretty neat tool/resource for learning about GraphQL. Though, to be honest, I think the scope of an HTGQL type resource/site is a bit larger than what I had in mind. The value is definitely there in such a resource existing though, so it shouldn't be ruled out for sure.

The biggest challenge to taking on something like HTGQL would be the design, the interactive features, and then finally the content creation. Full-blown tutorials with graphics and interactivity would be rather involved, so I imagine it would require getting others involved who have some good design experience.

From an implementation perspective though, it looks like HTGQL is using gatsby, which is a great framework for creating "static" websites using React, GraphQL, and other frontend tech that is common in the JS ecosystem, so if nothing else, inspiration could be taken from the tech that was used to create the site.

In regards to inspiration, I would also mention the below sites, which have historically done pretty well from the traditional documentation approach.

* https://tailwindcss.com/
* https://stripe.com/docs
* https://laravel.com/
* https://webpack.js.org/

My gut feeling is that something less ambitious than HTGQL would be better to tackle initially while the tech continues to build momentum and adopters, but I also do not have full context into what resourcing the Reactive Foundation may be able to leverage to make such projects more approachable.

**Comment by viglucci** [comment]
Closing as stale + https://github.com/rsocket/rsocket-website will/could likely cover these topics down the road.
