### ISSUE TITLE
rsocket-*@0.0.11 is missing build/* -- only has package.json

### ISSUE THREAD

**Issue by sandersn** [rsocket/rsocket-js#58]
Looks like an incorrect publish.

Discovered on Definitely Typed, which has types for rsocket-(tcp|websocket)-(client|server).
Here's the failure from the overnight run: https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=18518

If this is intentional, I'll remove those type packages from Definitely Typed.

**Comment by OlegDokuka** [comment]
Hi @sandersn! Not sure the failure is intentional but type definitions has done my community and seem to be a little incorrect in terms of following the original API. I'm going to take a loot at that thing later this week if it is not that urgent

**Comment by sandersn** [comment]
Well, in this case the *types* are fine -- 0.0.11 itself is a bad publish. There's no source code shipped with the package! So users who `npm install rsocket-tcp-client`, for example, will get a broken package.

**Comment by maxim-bandurko-lsvt** [comment]
@OlegDokuka Incorrect publish is for whole 0.0.11 version. At npm all packages have only package.json files:

https://registry.npmjs.org/rsocket-websocket-client/-/rsocket-websocket-client-0.0.11.tgz
https://registry.npmjs.org/rsocket-core/-/rsocket-core-0.0.11.tgz
https://registry.npmjs.org/rsocket-flowable/-/rsocket-flowable-0.0.11.tgz
https://registry.npmjs.org/rsocket-types/-/rsocket-types-0.0.11.tgz
....

**Comment by stevegury** [comment]
@sandersn Sorry for the trouble, could you try again with 0.0.16?

**Comment by sandersn** [comment]
Yep, looks like [the latest checks for `@types/rsocket-*` all passed](https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=19505). Thanks a lot!
