### ISSUE TITLE
Client keepalive flags seem strange

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-js#6]
Observed at http://rsocket-demo.herokuapp.com/

```
{
  "data": null,
  "flags": "FOLLOWS | RESPOND | RESUME_ENABLE (0x80)",
  "lastReceivedPosition": 2,
  "streamId": 0,
  "type": "KEEPALIVE (0x3)"
}
```

**Comment by lexs** [comment]
@yschimke Do you know if this is still true?

**Comment by yschimke** [comment]
How do I test? I think 0.0.1 was the one and only release of rsocket-js.

https://github.com/yschimke/rsocket-demo/blob/master/package.json

**Comment by lexs** [comment]
@yschimke We're up to 0.0.8: https://www.npmjs.com/package/rsocket-core (and family).

**Comment by yschimke** [comment]
Seems resolved,  also updated clients at the same time.  https://rsocket-demo.herokuapp.com/
