### ISSUE TITLE
rsocket-tcp-client dependencies err！

### ISSUE THREAD

**Issue by bojoyzhou** [rsocket/rsocket-js#67]
`rsocket-tcp-client` depend `rsocket-types` in code.
https://github.com/rsocket/rsocket-js/blob/master/packages/rsocket-tcp-client/src/RSocketTcpClient.js#L21
But it missed in package dependencies.
https://github.com/rsocket/rsocket-js/blob/master/packages/rsocket-tcp-client/package.json#L11

![image](https://user-images.githubusercontent.com/5258697/68913773-6d188100-0797-11ea-8141-d30a6f122512.png)

**Comment by OlegDokuka** [comment]
Hello, @bojoyzhou!

Can you please provide more information on how to reproduce that issue and what version you rely on in that case?

Regards,
Oleh

**Comment by OlegDokuka** [comment]
closed by https://github.com/rsocket/rsocket-js/commit/d392b39843faa455da98bfd7846993481c30937f
