### ISSUE TITLE
Allow metadata to be either "" or null

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket-js#7]
currently null, seems to become ""

```
{
  "data": "reactive",
  "flags": "METADATA (0x100)",
  "metadata": null,
  "requestN": 100,
  "streamId": 1,
  "type": "REQUEST_STREAM (0x6)"
}
```

**Comment by lexs** [comment]
@yschimke Are you saying sending `null` transparently changes it to the empty string?

**Comment by josephsavona** [comment]
I think this depends on which encoder you're using.

**Comment by yschimke** [comment]
That makes sense, IIRC around this time we were still fleshing out what it meant for metadata flag to be set/unset and the length in the frame encoding.  If rsocket-js allows null, "", and "a" as distinct metadata values now we can close.

**Comment by viglucci** [comment]
Closing as stale.
