### ISSUE TITLE
Support setupPayload for Typescript.

### ISSUE THREAD

**Issue by jjeffcaii** [rsocket/rsocket-js#70]
`ClientConfig` in `@types/rsocket-core` doesn't support setupPayload (include data and metadata). 

```typescript
// File: @types/rsocket-core/RSocketClient.d.ts
export interface ClientConfig<D, M> {
    serializers?: PayloadSerializers<D, M>;
    setup: {
        dataMimeType: string;
        keepAlive: number;
        lifetime: number;
        metadataMimeType: string;
    };
    transport: DuplexConnection;
    responder?: Partial<Responder<D, M>>;
}
```

**Comment by OlegDokuka** [comment]
Hi @jjeffcaii!

That has already been addressed and awaiting the release of rsocket-js before it goes to DefenitellyTyled repo.

Thanks a lot for asking.

Regards,
Oleh

**Comment by OlegDokuka** [comment]
@jjeffcaii  Also, before it went in, appreciate your early feedback on the provided fixes: https://github.com/OlegDokuka/DefinitelyTyped/tree/rsocket-latest-alignment

**Comment by jjeffcaii** [comment]
Thanks!
By the way, maybe we can include ts definition in rsocket-js repo directly. Just like `moment.d.ts` in https://github.com/moment/moment

**Comment by OlegDokuka** [comment]
I can do that. @rsocket/rsocket-js folks, don't you have any objections on that?

**Comment by kbahr** [comment]
TS is much more common in industry so even if the library isn't ported entirely, providing type definitions for interop would be great.

**Comment by adrianhopebailie** [comment]
I created the original TypeDefs because I was doing some experiments with rsocket and like to work in TypeScript. Would be very happy for them to be pulled into the libraries if someone is happy to keep maintaining them (as you can tell I am not doing a great job of maintaining them at DefinitelyTyped)
