### ISSUE TITLE
Version 0.17 and 0.18 gives "window is not defined" error

### ISSUE THREAD

**Issue by Polve** [rsocket/rsocket-js#74]
I'm trying to to a simple client to understand how the tech works and I can't even start the client with the latest release because I get this error:

```
ReferenceError: window is not defined
    at RSocketClient._checkConfig (/home/Work/rsocketjava/js/node_modules/rsocket-core/build/RSocketClient.js:94:23)
    at new RSocketClient (/home/Work/rsocketjava/js/node_modules/rsocket-core/build/RSocketClient.js:46:10)
    at Object.<anonymous> (/home/Work/rsocketjava/js/client.js:12:16)
    at Generator.next (<anonymous>)

```
The problem starts correctly using version 0.16.

My sample program is using the library with node, from the commandline.

**Comment by OlegDokuka** [comment]
Hello @Polve !

Thanks for reporting the issue! Fortunately we also observed that problem and has already provided the solution for that in #71 

Regards,
OIeh

**Comment by Polve** [comment]
Great! Waiting for an updated release to continue my tests and learning :-)

**Comment by OlegDokuka** [comment]
@Polve, should be fixed by #71. Let me know if anything related appears again. 
Feel free to check it from the master branch before the release.

Regards,
Oleh

**Comment by Polve** [comment]
I'm unable to do it for a while but thanks for the info :-)

**Comment by Polve** [comment]
Hello, a lot of time passed, can you please do a new release with this fix?

**Comment by stevegury** [comment]
@Polve Sorry for the delay, I just publish a new release (0.0.19).

**Comment by Polve** [comment]
Thanks @stevegury , greatly appreciated.
