### ISSUE TITLE
How to handle unexpected socket closures?

### ISSUE THREAD

**Issue by viglucci** [rsocket/rsocket-js#75]
What is the recommended way to handle unexpected socket closures when leveraging the WebSocket transport? For instance, if for some reason the server was to just die and the WebSocket connection to be terminated, what is the best way to hook into this event so that the user experience can be degraded gracefully?

I'm not seeing a way to hook into this event at the moment, but I do see that the WebSocket transport logs an error when it occurs (https://github.com/rsocket/rsocket-js/blob/master/packages/rsocket-websocket-client/src/RSocketWebSocketClient.js#L175).

My relevant code:

```js
// client.js
import {
    RSocketClient,
    BufferEncoders
} from 'rsocket-core';
import RSocketWebSocketClient from 'rsocket-websocket-client';

const transport = new RSocketWebSocketClient({
    url: 'ws://127.0.0.1:8081'
}, BufferEncoders);

// ms btw sending keepalive to server
const keepAlive = 60000 /* 60s in ms */;

// ms timeout if no keepalive response
const lifetime = 360000 /* 360s in ms */;

const client = new RSocketClient({
    setup: {
        keepAlive,
        lifetime,
    },
    transport
});

export default client;
```
```
client.connect().subscribe({
    onComplete: rsocket => {
        console.log("Success! We have established an RSocket connection.");
    },
    onError: error => {
        // this is only called on initialization failure
        console.log("Failed to connect to local RSocket server.", error);
    }
});
```

Is there an event that can be subscribed to on the client instance, or on the transport instance? Or perhaps a callback or something that can be passed in the construct args that I'm missing?

Thanks

**Comment by Polve** [comment]
I'm very interested in this scenario too

**Comment by OlegDokuka** [comment]
@viglucci the unexpected closures are propagated either in the 
```
client.connect().subscribe({
    onComplete: rsocket => {
        console.log("Success! We have established an RSocket connection.");
    },
    onError: error => { <- here are handled connection setup errors
        // this is only called on initialization failure
        console.log("Failed to connect to local RSocket server.", error); 
    }
});
```


or if the connection was handled but then unexpectedly closed, the only way to observe a failure is to subscribe to the following events stream

```
```
client.connect().subscribe({
    onComplete: rsocket => {
        console.log("Success! We have established an RSocket connection.");
        rsocket.connectionStatus().subscribe(status => console.log(status)); // <- if websocket was closed unexpectedly, that information will be propagated there (if available)
    },
    onError: error => { <- here are handled connection setup errors
        // this is only called on initialization failure
        console.log("Failed to connect to local RSocket server.", error); 
    }
});
```
