### ISSUE TITLE
Support for rsocket fragmentation

### ISSUE THREAD

**Issue by SerCeMan** [rsocket/rsocket-js#84]
Hi, RSocket-JS maintainers!

As far as I can tell, there is no support for fragmentation and reassembly is implemented in rsocket-js. It would be great to support it. As far as I can see, it's possible to take a similar approach to [FragmentationDuplexConnection.java](https://github.com/rsocket/rsocket-java/blob/develop/rsocket-core/src/main/java/io/rsocket/fragmentation/FragmentationDuplexConnection.java), e.g. provide a connection wrapper.

**Comment by OlegDokuka** [comment]
@SerCeMan, thank you for reporting that!

Putting in the backlog right after java release. 
So it should be this / next month.

Regards,
Oleh

**Comment by progys** [comment]
> @SerCeMan, thank you for reporting that!
> 
> Putting in the backlog right after java release.
> So it should be this / next month.
> 
> Regards,
> Oleh

We faced some problem with uploading file via RSocket, because of too large frame length. Fragmentation would be a very simple and nice solution to it! Cannot wait until it gets supported. Thanks for you great work!

**Comment by OlegDokuka** [comment]
@SerCeMan @progys i will fix that this week. Stay tuned and I really thank you for your patience

**Comment by progys** [comment]
> @SerCeMan @progys i will fix that this week. Stay tuned and I really thank you for your patience

Any news on this? Sorry to be pushy :)

**Comment by OlegDokuka** [comment]
@SerCeMan @progys 
Landed a PR which adds Reassembly support, do you need fragmentation support as well?

**Comment by progys** [comment]
> @SerCeMan @progys
> Landed a PR which adds Reassembly support, do you need fragmentation support as well?

I think that would be very useful. Thank you!

**Comment by OlegDokuka** [comment]
@progys sure. I see your use case. I will try to add it sooner, but just want to say that I have some plans on rewriting rsocket-js to TS and do not wanna spend much time on introducing temporary solutions. But if it is urgent and really needed, I can do that

**Comment by raphael-jungers** [comment]
Hi @OlegDokuka,

Is fragmentation also implemented in #102 ? And is there a way to already use these new features without a new npm release ? Thank you !
