### ISSUE TITLE
[rsocket-tcp-client] RSocketTlsClient not exported from package index

### ISSUE THREAD

**Issue by guybarnard** [rsocket/rsocket-js#86]
I am trying to use [RSocketTlsClient](https://github.com/rsocket/rsocket-js/blob/master/packages/rsocket-tcp-client/src/RSocketTcpClient.js#L234) in order to connect over secure transports.

I can import it directly from `rsocket-tcp-client/build/RSocketTcpClient` but would prefer not to rely on the structure of the build repository, and import from `rsocket-tcp-client`.   Is there any reason its not exported directly in [rsocket-tcp-client/src/index.js](https://github.com/rsocket/rsocket-js/blob/master/packages/rsocket-tcp-client/src/index.js) ?

### Workaround
``` js
import { RSocketTlsClient } from 'rsocket-tcp-client/build/RSocketTcpClient'
import RSocketTcpClient from 'rsocket-tcp-client'
```

### Desired
``` js
import RSocketTcpClient, { RSocketTlsClient } from 'rsocket-tcp-client'
```

### Use case
Custom Flipper Client that runs on desktop/node and requires RSocket transport over TLS

**Comment by viglucci** [comment]
Hey @guybarnard,

Sorry I know it has been a _very long while_ with essentially radio silence on this issue, however, I am wondering if you have a suggestion for how the exports would look from `rsocket-tcp-client/src/index.js`?

I'm not sure which syntax would accomplish what you are looking for.

Thanks

**Comment by viglucci** [comment]
I believe this would accomplish what you are looking for?

```js
import * as RSocketTcpClient from './RSocketTcpClient';

export default RSocketTcpClient.RSocketTcpClient;
export const RSocketTlsClient = RSocketTcpClient.RSocketTlsClient;
export const RSocketTcpConnection = RSocketTcpClient.RSocketTcpConnection;

```

**Comment by viglucci** [comment]
Closing as stale, Please let us know if this issue is still relevant.
