### ISSUE TITLE
[Request] new release please

### ISSUE THREAD

**Issue by LifeIsStrange** [rsocket/rsocket-js#87]
Our enterprise product depend on 
https://github.com/rsocket/rsocket-js/commit/cde81cd793f7b60f00085e398543e8687b7964f1
or more precisely on MESSAGE_RSOCKET_AUTHENTICATION support

**Comment by viglucci** [comment]
@OlegDokuka is there a release planned to include the changes from https://github.com/rsocket/rsocket-js/commit/cde81cd793f7b60f00085e398543e8687b7964f1 ?

It appears that the latest release to npm was about 4 months ago for version 0.0.19, however there have been more recent additions to master. If there are blockers/logistics issues with pushing a release, is there anything the community can do to help?

Thanks

**Comment by OlegDokuka** [comment]
@viglucci let me try to arrange that next week. I was busy with RSocket-Java most of the time. Thus was not able to provide a few more fixes need for a release

Cheers,
Oleh

**Comment by Pheromon** [comment]
Interested in updated release too :-)

**Comment by LifeIsStrange** [comment]
@OlegDokuka please take your time, yes we all want a release but what matters even more is to not introduce bugs/regressions and suboptimal APIs that would require breaking changes in follow-up releases.
I'm just stating the obvious, but take your time and release it when it's ready™
And we are all grateful for your work!
