### ISSUE TITLE
[Question] Usage of RSocket Bearer authentication MIME type

### ISSUE THREAD

**Issue by HugoKempfer** [rsocket/rsocket-js#88]
Hi, I recently saw that with https://github.com/rsocket/rsocket-js/commit/cde81cd793f7b60f00085e398543e8687b7964f1, the `message/x.rsocket.authentication.v0` MIME Type will be provided.

But I wonder how to actually use it with the *SETUP* frame metadata.
As my server implementation uses Spring security RSocket and *Jwt* authorization strategy, the jwt bearer token is expected to be provided through the SETUP frame metadata under the previous MIME type.

If my understanding is correct the `RsocketClient` `setup` object only allows us to specify a global `metadataMimeType`.

This code snippet below is my current typescript client configuration.

```typescript
RSocketClient({
      serializers: {
        data: JsonSerializer,
        metadata: JsonSerializer,
      },
      setup: {
        keepAlive: 60000,
        lifetime: 180000,
        dataMimeType: APPLICATION_JSON.string,
        metadataMimeType: MESSAGE_RSOCKET_ROUTING.string,
        payload: {
          metadata: JWT, // interpreted as Setup route ?
        },
      },
      transport: new RSocketWebSocketClient({
        url: "ws://localhost:8085",
      }),
    }
```
I only have a shallow understanding of the RSocket protocol and as the Java/Kotlin `RSocketRequester` client let me use a request wise MIME Type, I have no clue on how to comply with my RSocket server Authorization without this feature.

Here is the equivalent Kotlin version of this client demonstrating the use of the MIME type:

```kotlin
    fun createRsocketRequester(jwt: String): RSocketRequester? {
        val tokenMimeType = MimeType.valueOf("message/x.rsocket.authentication.bearer.v0")
        val strategies = RSocketStrategies.builder().encoders {
                    it.add(Jackson2CborEncoder())
                    it.add(ByteBufferEncoder())
                    it.add(Jackson2JsonEncoder())
                }
                .decoders {
                    it.add(Jackson2CborDecoder())
                    it.add(ByteBufferDecoder())
                    it.add(Jackson2JsonDecoder())

                }
                .build()

        return RSocketRequester.builder()
                .rsocketStrategies(strategies)
                .setupMetadata(jwt, tokenMimeType)
                .connectWebSocket(URI.create("ws://${this.serverHost}:${this.serverPort}")).doOnError{
                    System.err.println("Rsocket REQUESTER error: ${it.message} cause ${it.cause}")
        }.block()
    }
}
```

I'd really appreciate any help with this :)

**Comment by OlegDokuka** [comment]
cc @rwinch

**Comment by OlegDokuka** [comment]
@HugoKempfer the proper codec should be in place. I will add them shortly

**Comment by rwinch** [comment]
> As my server implementation uses Spring security RSocket and Jwt authorization strategy, the jwt bearer token is expected to be provided through the SETUP frame metadata under the previous MIME type.

@HugoKempfer Spring Security added support for the[ RSocket Authentication Extension](https://github.com/spring-projects/spring-security/issues/7935) (the new mechanism) in Spring Security 5.3.0. You can read about it in the [RSocket JWT section of the reference](https://docs.spring.io/spring-security/site/docs/5.3.x/reference/html5/#rsocket-authentication-jwt). Does this help?

**Comment by HugoKempfer** [comment]
Hi, thanks for those answers!

@rwinch for the server-side, I already rely on the Bearer Token Authentication Metadata Extension of Spring Security 5.3.0 and it works well!
I use the `RSocketRequester` java client to test my server in integration testing.
As the `RSocketRequester` allows me to provide a MIME type as demonstrated in the reference, this works fine.
```java
MimeType authenticationMimeType =
    MimeTypeUtils.parseMimeType(WellKnownMimeType.MESSAGE_RSOCKET_AUTHENTICATION.getString());
BearerTokenMetadata token = ...;
Mono<RSocketRequester> requester = RSocketRequester.builder()
    .setupMetadata(token, authenticationMimeType)
    .connectTcp(host, port);
```
What I'm seeking is to produce the equivalent encoding with the JS/TS client.

@OlegDokuka I don't really understand what is a codec in this context, an equivalent to `IdentitySerializer` for jwt? Or a method to encode the metadata buffer like `encodeAndAddWellKnownMetadata` ? What will the API look like?

**Comment by OlegDokuka** [comment]
@HugoKempfer I was talking about > https://github.com/rsocket/rsocket-java/blob/master/rsocket-core/src/main/java/io/rsocket/metadata/AuthMetadataCodec.java#L31

**Comment by jg513** [comment]
```typescript
const SETUP = "setup";
new RSocketClient({
    setup: {
        payload: {
            data: '',
            metadata: encodeAndAddCustomMetadata(
                encodeAndAddWellKnownMetadata(
                    Buffer.alloc(0),
                    MESSAGE_RSOCKET_ROUTING,
                    Buffer.from(String.fromCharCode(SETUP.length) + SETUP)
                ),
                'message/x.rsocket.authentication.v0',
                token ? this.bearerToken(token) : this.simpleAuth(username, password)
            )
        },
        ...
    },
    ...
})
```

```typescript
simpleAuth(username: string, password: string): Buffer {
        const buffer = Buffer.alloc(2 + username.length + password.length);
        buffer.writeUInt8(0 | 0x80, 0);
        buffer.writeUInt8(username.length, 1);
        buffer.write(username, 2, 'utf-8');
        buffer.write(password, 2 + username.length, 'utf-8');
        return buffer;
}
```

```typescript
bearerToken(token: string): Buffer {
        const buffer = Buffer.alloc(1 + token.length);
        buffer.writeUInt8(0 | 0x80, 0);
        buffer.write(token, 1, 'utf-8');
        return buffer;
}
```

I want to use the authentication MIME type, so I use this hard-coded snippet.

Looking forward to the new version with auth metadata codec.

**Comment by joao8991** [comment]
Hi @jg513 I'm trying to do a auth by jwt but I'm having:
`RSocketEncoding: Expected value to be a string, got `�\u0000\u0000\n\tclient-id)message/x.rsocket.authentication.bearer.v0\u0000\u0003\u0017�eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InZlcnNpb24xIn0.eyJzdWIiOiJtb2NrLXRlbmFudC1wb29sOjhhMDkyNjEwLTVjNzUtMTFlYS1iYzU1LTAyNDJhYzEzMDAwMyIsInNjb3BlIjoiZW1haWwgb3BlbmlkIHByb2ZpbGUiLCJpc3MiOiJhdXRoLm1hbm5vdy5pbnQtY2NwLWRldi5uZXQiLCJleHAiOjE2MDY5MzU0NjUsImlhdCI6MTYwNjkzMTg2NSwianRpIjoiZTZhYjFiZmQtYjAzMC00NDRiLThmNDItZWZmYjRlNDljMmQ1IiwiYWNjb3VudCI6IjIyZjc4ZDVmLTRmNGQtNGEwOC1iNWMyLTUwM2IxZDhmY2JhZCIsImF6cCI6ImNsaWVudDEiLCJ0ZW5hbnQiOiJtb2NrIn0.2j5DosJSgU6U6VHSPwrGJ0ajLmPZOVcsIuO4B0gJhXzPwzjB9eXrBBtRpatGTTh2Tle0R9MWGuf3WnptbWygi5eZ-FMr9PRZVit5Dg5pOLh8IAUY9zH3986ipEx4gMOY6zHnpl_93Sq9MjW0MSBxg0PiutDCB6_TSkN6GYrGqTHeLmSxtylVz7p044uvXhBMYKYxtczdRWlIrpYGLP1KaD9oZMRJcwygkiMbXsUt3m3MAnXZR5QjEcMiQ2OJSRTqzk-WhbL6PLAbf8VK9LfTbjN_uuZpKfhoexwRm5QtXtIKcT-q5EwhYo6gBvBIu_LQIY2QRiIIBUBEVA9UMwa0zw`.`

and this is my client config:
`client = new RSocketClient({
    serializers: {
      data: JsonSerializer,
      metadata: IdentitySerializer
    },
    setup: {
      keepAlive: 60000,
      lifetime: 180000,
      dataMimeType: 'application/octet-stream',
      metadataMimeType: MESSAGE_RSOCKET_COMPOSITE_METADATA.string,
      payload: {
        data: Buffer.from(username),
        // metadata: String.fromCharCode("client-id".length) + "client-id"
        metadata: encodeAndAddCustomMetadata(
          encodeAndAddWellKnownMetadata(
            Buffer.alloc(0),
            MESSAGE_RSOCKET_ROUTING,
            Buffer.from(String.fromCharCode("client-id".length) + "client-id")
          ),
          "message/x.rsocket.authentication.bearer.v0",
          bearerToken(token),
        ),
      }
    },
    responder: new Responder(),
    transport: new RSocketWebSocketClient({
      url: 'ws://localhost:8888',
      BufferEncoders,
    }),
  });`

**Comment by jg513** [comment]
@joao8991 

```typescript
bearerToken(token: string): Buffer {
    const buffer = Buffer.alloc(1 + token.length);
    buffer.writeUInt8(1 | 0x80, 0);
    buffer.write(token, 1, 'utf-8');
    return buffer;
}
````

**Comment by Braffolk** [comment]
@joao8991

Did you get your issue fixed? I'm having the same problem.

**Comment by joao8991** [comment]
@jg513 thanks for the hint but I already had that method implemented. @Braffolk no.

**Comment by jg513** [comment]
@joao8991 

```typescript
new RSocketClient({
    setup: {
        payload: {
            data: '',
            metadata: encodeAndAddCustomMetadata(
                encodeAndAddWellKnownMetadata(
                    Buffer.alloc(0),
                    MESSAGE_RSOCKET_ROUTING,
                    Buffer.from(String.fromCharCode(SETUP.length) + SETUP)
                ),
                'message/x.rsocket.authentication.v0',
                token ? this.bearerToken(token) : this.simpleAuth(username, password)
            )
        },
        dataMimeType: APPLICATION_JSON.string,
        metadataMimeType: MESSAGE_RSOCKET_COMPOSITE_METADATA.string,
        keepAlive: 60000,
        lifetime: 1000000,
    },
    transport: new RSocketWebSocketClient({
        url: url,
        wsCreator: url => new WebSocket(url)
    }, {
        data: UTF8Encoder,
        dataMimeType: UTF8Encoder,
        message: UTF8Encoder,
        metadata: BufferEncoder,
        metadataMimeType: UTF8Encoder,
        resumeToken: BufferEncoder,
    })
});
```

**Comment by Braffolk** [comment]
> @jg513 thanks for the hint but I already had that method implemented. @Braffolk no.

I have it fixed. Since you are providing buffers to it and not strings, your RSocketClient also needs BufferEncoders. Like this:
```JavaScript
new RSocketClient({
            "serializers": {
                ...
            },
            "setup": {
                ...
            },
            "transport": new RSocketWebSocketClient({
                "url": this.url
            }, BufferEncoders)
        });
```

Notice that BufferEncoders is an argument of RSocketClient, not part of any object. I accidentally had it in the transport RSocketWebSocketClient.

**Comment by OlegDokuka** [comment]
For everybody interested in the topic. Now we support all the composite metadata needed;

```js
RSocketClient({
      serializers: {
        data: JsonSerializer,
        metadata: JsonSerializer,
      },
      setup: {
        keepAlive: 60000,
        lifetime: 180000,
        dataMimeType: APPLICATION_JSON.string,
        metadataMimeType: MESSAGE_RSOCKET_COMPOSITE_METADATA.string,
        payload: {
          metadata: encodeCompositeMetadata([
                 [TEXT_PLAIN, Buffer.from('Hello World')],
                 [MESSAGE_RSOCKET_ROUTING, encodeRoute("my.route")],
                 [MESSAGE_RSOCKET_AUTHENTICATION, encodeBearerAuthMetadata(JWT)],
          ])
        },
      },
      transport: new RSocketWebSocketClient({
        url: "ws://localhost:8085",
      }),
    }
```
