### ISSUE TITLE
RequestResponse requests shouldn't get data in the onComplete callback

### ISSUE THREAD

**Issue by codependent** [rsocket/rsocket-js#89]
The full context of this issue can be found on this SO question: https://stackoverflow.com/questions/62119541/rsocket-js-client-not-getting-elements-generated-from-a-spring-boot-rsocket-serv/62120181

**Comment by viglucci** [comment]
Reviewing the implementation for `requestResponse` we see that it returns a `Single` from `rsocket-flowable`, which only implements `onComplete` via `IFutureSubscriber`. Given that, I'm not sure that this is actually something we should address, in that it appears that the internals of `rsocket-js` are properly handling the frame flags as indicated in the Protocol, it is just that the interfaces implements in `rsocket-flowable` do not match 1:1 to other reactive streams implementations. In my opinion, I think that this is acceptable as a characteristic of `rsocket-flowable`, but maybe something that should be kept in mind/re-visited should `rsocket-flowable` be overhauled down the road.

```
  /**
   * Request-Response interaction model of `ReactiveSocket`. The returned
   * Publisher resolves with the response.
   */
  requestResponse(payload: Payload<D, M>): Single<Payload<D, M>>;
```
