### ISSUE TITLE
how to handle a reject connect?

### ISSUE THREAD

**Issue by anuger** [rsocket/rsocket-js#95]
**rsocket-java**
``` java
RSocketServer.create()
                .acceptor((setupPaylod, rSocket) -> Mono.error(new RejectedSetupException("reject")))
                .payloadDecoder(PayloadDecoder.ZERO_COPY)
                .bind(WebsocketServerTransport.create(8080))
                .doOnSuccess(it -> log.info("started"))
                .block());
```
**rsocket-js**
``` javaScript
let rSocketClient = new RSocketClient({
    serializers: JsonSerializers,
    setup: {
      keepAlive: 2000,
      lifetime: 5000,
      dataMimeType: 'application/json',
      metadataMimeType: 'text/plain'
    },
    transport: new RSocketWebSocketClient({url: "ws://localhost:8080"}),
  });
rSocketClient.connect()
        .subscribe({
          onComplete: (rSocket) => {
            console.log(rSocket)
          },
          onError: (error) => {
            console.log("error" + error.message)
          }
        })
```
I hope get the print with "error: reject"
but I get 
![image](https://user-images.githubusercontent.com/24793128/88198718-923e8700-cc76-11ea-98c9-63b1ce612ce2.png)

**Comment by jjeffcaii** [comment]
@OlegDokuka  I've tested in local environment and it seems a bug. I think client should throw an error if server rejects the incoming connection.
![image](https://user-images.githubusercontent.com/1284892/88273581-fc097000-cd0c-11ea-8a05-9644fba55343.png)

**Comment by OlegDokuka** [comment]
Alright. Can be. I will take a look at that shortly

**Comment by OlegDokuka** [comment]
Have not spotted that from the beginning, but, the mentioned behaviors are correct. In the default setup (no leasing and no resumability enabled) RSocket protocol does not have a handshake phase (for more info see -> https://rsocket.io/docs/Protocol.html#connection-establishment) and follows False Start behavior. That said, the `onError` handler may occur only if the underlying transport connection handshake has failed. In all other cases, the client assumes successful acceptance of the setup payload and the only way to observe RSocket failure is via the `conenctionStatus` handler:

```
client.connect().then(socket => {
  socket.connectionStatus().subscribe(event => console.log(event));
});
```
